abstract_target 'Starter' do
  use_frameworks!
  # Pods for all targets
  pod 'MetaWear', :subspecs => ['AsyncUtils', 'UI'], :path => '../'
  pod 'Bolts-Swift', :git => 'https://github.com/BoltsFramework/Bolts-Swift.git', :commit => 'e9baa72'

  target 'iOS' do
    platform :ios, '10.0'

    # Pods for iOS
    pod 'MBProgressHUD'
  end

  target 'macOS' do
    platform :osx, '10.13'

    # Pods for macOS
  end

  target 'tvOS' do
    platform :tvos, '10.0'

    # Pods for tvOS
    pod 'MBProgressHUD'
  end
end

