# Uncomment this line to define a global platform for your project
platform :ios, '10.0'
use_frameworks!

target 'MetaWearApp' do
  pod 'MetaWear', :subspecs => ['AsyncUtils', 'UI', 'DFU']
  pod 'MBProgressHUD'
  pod 'StaticDataTableViewController'
end

